CREDENTIALS_FILENAME = "nodal-wall-416914-5876acf16f70.json"
BEO_WORKSHEET_ID = 2121169814
KIMITTUD_WORKSHEET_ID = 858480548
MASTER_SHEET_ID = "1fwhZxPtuP2MSBkTXJRSH-plXGV42mF-HlQPf4KSpFwE"
NAMES = [
    "ALEX",
    "BALU",
    "BELLA",
    "BENDEGÚZ",
    "BENI",
    "BORCSA",
    "BORI",
    "CSABI",
    "DÁVID",
    "DORINA",
    "DORKA",
    "EMMA",
    "FANNI",
    "GÁBOR",
    "GERGŐ",
    "JANKA",
    "KATA",
    "KRISTÓF",
    "LILI",
    "LILLA",
    "MARIANN",
    "MÁRK",
    "NIKI",
    "RÉKA",
    "SANYI",
    "SÁRI",
    "TAKI",
    "VANDA",
    "PANKA",
    "VERONKA",
    "SP",
    "ROSI",
]
